[package]
name = "triangle_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
png = "0.17.7"
serde_json = "1.0.87"
serde = {version ="1.0.147", features=["derive"]}